name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # ⬅️ biar bisa run manual dari GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Lint
        run: bun run lint

      - name: Run Type Check
        run: bun run type-check

      - name: Run Tests with Coverage
        run: bun run test -- --coverage
